name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Dispatch build to kaniko.jrcichra.dev
        id: dispatch
        uses: jrcichra/kaniko-dispatcher@main
        with:
          name: cockroachdb-multiarch
          url: https://kaniko.jrcichra.dev
          context: "git://github.com/jrcichra/cockroachdb-multiarch#${{ github.sha }}"
          destination: "ghcr.io/jrcichra/cockroachdb-multiarch:sha-${{ steps.vars.outputs.sha_short }}-amd64"
          secret: justin-ghcr-io
          arch: amd64
          headers: |
            {
              "CF-Access-Client-Id" : "93a12e585dcfcf01442b6c75444a228b.access",
              "CF-Access-Client-Secret" : "${{ secrets.ORACLE_K8S_ACCESS_TOKEN }}"
            }

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Dispatch build to kaniko.jrcichra.dev
        id: dispatch
        uses: jrcichra/kaniko-dispatcher@main
        with:
          name: cockroachdb-multiarch
          url: https://kaniko.jrcichra.dev
          context: "git://github.com/jrcichra/cockroachdb-multiarch#${{ github.sha }}"
          destination: "ghcr.io/jrcichra/cockroachdb-multiarch:sha-${{ steps.vars.outputs.sha_short }}-arm64"
          secret: justin-ghcr-io
          arch: arm64
          headers: |
            {
              "CF-Access-Client-Id" : "93a12e585dcfcf01442b6c75444a228b.access",
              "CF-Access-Client-Secret" : "${{ secrets.ORACLE_K8S_ACCESS_TOKEN }}"
            }

  combine-manifests:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Combine manifests
        run: .github/build/manifest.sh
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          SHA: ${{ github.sha }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
